const images = {
    specificationImg: require('./specification-img.webp'),
    companionImg: require('./companion.webp'),
    popupProductImg: require('./Popup-product.webp'),
    abilityImg01: require('./ability-01.webp'),
    abilityImg02: require('./ability-02.webp'),
    abilityImg03: require('./ability-03.webp'),
    abilityImg04: require('./ability-04.webp'),
    abilityImg05: require('./ability-05.webp'),
    abilityImg06: require('./ability-06.webp'),
    homeProductMainImg01: require('./home-product-main-01.webp'),
    homeProductMainImg02: require('./home-product-main-02.webp'),
    homeProductMainImg03: require('./home-product-main-03.jpg'),
    homeProductMainImg04: require('./home-product-main-04.jpg'),
    homeProduct01: require('./home-product-01.webp'),
    homeProduct02: require('./home-product-02.avif'),
    homeProduct03: require('./home-product-03.avif'),
    homeProduct04: require('./home-product-04.avif'),
    testimonialImg01: require('./testimonial-01.png'),
    testimonialImg02: require('./testimonial-02.png'),
    testimonialImg03: require('./testimonial-03.png'),
    blogImg01: require('./blog-01.jpg'),
    blogImg02: require('./blog-02.jpg'),
};
export default images;
