spring:
  application:
    name: timevo_ecommerce_backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/website_timevo_ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Timevo@230523}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: timevo.service@gmail.com
    password: dmweoodnebrrolrm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  redis:
    host: ${REDIS_HOST:localhost} # Default to 'localhost' if not provided
    port: ${REDIS_PORT:6379}      # Default to 6379 if not provided
  #flyway
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
api:
  prefix: /api/v1
jwt:
  expiration: 2592000 #30 days
  expiration-refresh-token: 5184000 #60 days
  secretKey: jtc6zcRYQr5lZj4UCIwkIbLjpP/AhDbSiZhUHa5VoGw=

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: QNXWOWFK
    secretKey: XUVRV7PLKWLSH9WA0ULLK7OFVLA416RS
    returnUrl: http://localhost:8080/api/v1/payments/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

logging:
  level:
    org:
      springframework.security: DEBUG

# Swagger-UI custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# Health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"