const routes = {
    home: '/',
    shop: '/shop',
    about: '/about',
    blog: '/blog/news',
    faq: '/faq',
    contact: '/contact',
    register: '/register',
    login: '/login',
    detail: '/products/:productId',
    // accountStatus: '/account-status/:email?/:activeCode?',
    accountStatus: '/active-account/:email?/:activeCode?',
    checkout: '/checkout',
    cart: '/cart',
    wishlist: '/wishlist',
    orderSuccessful: '/order-successful',
    compare: '/compare',
    pageNotFound: '/404-not-found',
    forgotPassword: '/forgot-password',
    forgotPasswordOTP: '/forgot-password/otp/:email?',
    forgotPasswordNew: '/forgot-password/new/:email?/:otp?',
    changePassword: '/change-password/:email',
    profile: '/customer/profile',
    orderDetails: '/customer/order-details/:orderId',
    searchResult: '/search',

    adminDashboard: '/admin/dashboard',
    adminCustomers: '/admin/customers',
    adminNewCustomer: '/admin/customer/new',
    adminEditCustomer: '/admin/customer/edit/:customerId',
    adminDetailCustomer: '/admin/customer/detail/:customerId',
    adminProducts: '/admin/products',
    adminNewProduct: '/admin/product/new',
    adminEditProduct: '/admin/product/edit/:productId',
    adminOrders: '/admin/orders',
    adminOrderDetails: '/admin/order-details/:orderId',
};

export default routes;
